name: Viral_Video_Machine
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # Rozana subah 10 AM GMT par chalega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          sudo sed -i 's/domain="path" rights="none" pattern="@\*"/domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml

      - name: Install Python Packages
        run: |
          pip install google-generativeai edge-tts moviepy==1.0.3 requests

      - name: Run AI Machine
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Save Video Result
        uses: actions/upload-artifact@v4
        with:
          name: AI-Viral-Short
          path: viral_short.mp4
